language: php

php:
  - 7.1.13
  - 7.1.14
  - 7.2

before_script:
  - cp .env.travis .env
  - mysql -e 'create database nobrainer;'
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit
